### ISSUE TITLE
Error on last step

### ISSUE THREAD

**Issue by holic-cl** [Anewri32/POAutotranslate#1]
Hi!, i came to say thanks, works like charm, it works very well at first run!

Only a not important error i got when it finnish, show this log
```
Traceback (most recent call last):
  File "/home/holic/po-trans/main.py", line 132, in <module>
    process_file(file_name)
  File "/home/holic/po-trans/main.py", line 87, in process_file
    print(get_progress_bar(100, get_text_color('File: ' + file_out + ' saved', 'green')))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/holic/po-trans/src/TextStyler.py", line 19, in get_progress_bar
    progress_float = percent / 100 * long_bar
                     ~~~~~~~~~~~~~~^~~~~~~~~~
TypeError: can't multiply sequence by non-int of type 'float'
```

Thanks a lot again!

**Comment by Anewri32** [comment]
Greetings, the bug has been fixed, thanks for the report! :)
I'll upload the release soon.

Commit related: https://github.com/Anewri32/POAutotranslate/commit/2540558c27bb28209fe9892d03c0eed6b98b507b
